name: Android build & release

on:
  push:
    branches: [ main ]

jobs:
  flutter_test:
    name: Flutter Test and Analyse
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version
      - run: flutter pub get
      - run: flutter pub upgrade
      - run: flutter build apk --debug --no-tree-shake-icons --debug --dart-define SERVER-URL=${{ secrets.SERVER_URL }} --dart-define IRBS-SERVER-URL=${{ secrets.IRBS_SERVER_URL }} --dart-define SECURITY-KEY=${{ secrets.SECURITY_KEY }} --dart-define GMAP_KEY=${{ secrets.GMAP_KEY }} --dart-define GITHUB_ISSUE_TOKEN=${{ secrets.GIT_TOKEN }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-debug.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GIT_TOKEN }}

