name: Pull Request build test

on:
  pull_request:
    branches: [ main ]

jobs:
  flutter_test:
    name: Run Flutter Test and Analyse
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Setting up Java
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: '21'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - run: flutter pub get
      - run: flutter pub upgrade
      - run: flutter build apk --no-tree-shake-icons --debug
